# Generated by Django 4.1.4 on 2022-12-22 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_delete_car_delete_driver_delete_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_grada', models.CharField(max_length=64, verbose_name='Ime grada')),
                ('drzava', models.CharField(max_length=64, verbose_name='Drzava u kojoj se nalazi: ')),
            ],
        ),
        migrations.CreateModel(
            name='Lokacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=64, verbose_name='Ime')),
                ('zem_sirina', models.CharField(max_length=64, verbose_name='Zemljopisna sirina')),
                ('zem_duzina', models.CharField(max_length=64, verbose_name='Zemljopisna duzina')),
                ('grad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.grad')),
            ],
        ),
        migrations.CreateModel(
            name='TrenutnoVrijeme',
            fields=[
                ('lokacija', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.lokacija')),
                ('temperatura', models.CharField(max_length=6)),
                ('vlaga', models.CharField(max_length=3)),
                ('tlak', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PrognoziranoVrijeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(max_length=6)),
                ('vlaga', models.CharField(max_length=3)),
                ('tlak', models.CharField(max_length=5)),
                ('datum_i_vrijeme', models.DateTimeField(default=django.utils.timezone.now)),
                ('lokacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lokacija')),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=64, verbose_name='Ime')),
                ('prezime', models.CharField(max_length=64, verbose_name='Prezime')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('fav_lokacije', models.ManyToManyField(to='main.lokacija')),
            ],
        ),
    ]
